all:
	LIBRARY_PATH=/home/avagin/git/api/libcontainer/libct/libct/.shipped/libnl/lib/.libs:/home/avagin/git/api/libcontainer/libct/libct/ go build -o nsinit config.go exec.go init.go main.go nsenter.go pause.go stats.go utils.go
